# Generated by Django 2.0.5 on 2018-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colori',
            fields=[
                ('codice', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('colore', models.CharField(max_length=30)),
            ],
        ),
    ]
