# Generated by Django 2.0.5 on 2018-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giochi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifica',
            name='gioco',
            field=models.CharField(default='', max_length=30),
        ),
    ]
