# Generated by Django 2.0.5 on 2018-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giochi', '0003_classifica_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifica',
            name='user',
            field=models.CharField(default='Anonimo', max_length=30),
        ),
    ]
